# a theme based on the application's `default` theme
[[themes]]
name = "default2"
[themes.palette]
# default theme doesn't have `foreground` and `background` specified
black = "black"
red = "red"
green = "green"
yellow = "yellow"
blue = "blue"
magenta = "magenta"
cyan = "cyan"
white = "white"
bright_black = "bright_black"
bright_red = "bright_red"
bright_green = "bright_green"
bright_yellow = "bright_yellow"
bright_blue = "bright_blue"
bright_magenta = "bright_magenta"
bright_cyan = "bright_cyan"
bright_white = "bright_white"

[[themes]]
name = "dracula"
[themes.palette]
background = "#1e1f29"
foreground = "#f8f8f2"
black = "#000000"
red = "#ff5555"
green = "#50fa7b"
yellow = "#f1fa8c"
blue = "#bd93f9"
magenta = "#ff79c6"
cyan = "#8be9fd"
white = "#bbbbbb"
bright_black = "#555555"
bright_red = "#ff5555"
bright_green = "#50fa7b"
bright_yellow = "#f1fa8c"
bright_blue = "#bd93f9"
bright_magenta = "#ff79c6"
bright_cyan = "#8be9fd"
bright_white = "#ffffff"

# same colors as dracula, but includes non-default component styles
[[themes]]
name = "dracula2"
[themes.palette]
background = "#1e1f29"
foreground = "#f8f8f2"
black = "#000000"
red = "#ff5555"
green = "#50fa7b"
yellow = "#f1fa8c"
blue = "#bd93f9"
magenta = "#ff79c6"
cyan = "#8be9fd"
white = "#bbbbbb"
bright_black = "#555555"
bright_red = "#ff5555"
bright_green = "#50fa7b"
bright_yellow = "#f1fa8c"
bright_blue = "#bd93f9"
bright_magenta = "#ff79c6"
bright_cyan = "#8be9fd"
bright_white = "#ffffff"
[themes.component_style]
like = { fg = "Red", modifiers = ["Bold"] }
selection = { bg = "Black", fg = "White", modifiers = ["Bold"] }
secondary_row = { bg = "#677075" }

[[themes]]
name = "gruvbox-dark"
[themes.palette]
background = "#282828"
foreground = "#ebdbb2"
black = "#282828"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#a89984"
bright_black = "#928374"
bright_red = "#fb4934"
bright_green = "#b8bb26"
bright_yellow = "#fabd2f"
bright_blue = "#83a598"
bright_magenta = "#d3869b"
bright_cyan = "#8ec07c"
bright_white = "#ebdbb2"

[[themes]]
name = "gruvbox-light"
[themes.palette]
background = "#fbf1c7"
foreground = "#282828"
black = "#fbf1c7"
red = "#9d0006"
green = "#79740e"
yellow = "#b57614"
blue = "#076678"
magenta = "#8f3f71"
cyan = "#427b58"
white = "#3c3836"
bright_black = "#9d8374"
bright_red = "#cc241d"
bright_green = "#98971a"
bright_yellow = "#d79921"
bright_blue = "#458588"
bright_magenta = "#b16186"
bright_cyan = "#689d69"
bright_white = "#7c6f64"

[[themes]]
name = "solarized-dark"
[themes.palette]
background = "#002b36"
foreground = "#839496"
black = "#073642"
red = "#dc322f"
green = "#859900"
yellow = "#b58900"
blue = "#268bd2"
magenta = "#d33682"
cyan = "#2aa198"
white = "#eee8d5"
bright_black = "#002b36"
bright_red = "#cb4b16"
bright_green = "#586e75"
bright_yellow = "#657b83"
bright_blue = "#839496"
bright_magenta = "#6c71c4"
bright_cyan = "#93a1a1"
bright_white = "#fdf6e3"

[[themes]]
name = "solarized-light"
[themes.palette]
background = "#fdf6e3"
foreground = "#657b83"
black = "#073642"
red = "#dc322f"
green = "#859900"
yellow = "#b58900"
blue = "#268bd2"
magenta = "#d33682"
cyan = "#2aa198"
white = "#eee8d5"
bright_black = "#002b36"
bright_red = "#cb4b16"
bright_green = "#586e75"
bright_yellow = "#657b83"
bright_blue = "#839496"
bright_magenta = "#6c71c4"
bright_cyan = "#93a1a1"
bright_white = "#fdf6e3"

[[themes]]
name = "tokyonight"
[themes.palette]
background = "#1f2335"
foreground = "#c0caf5"
black = "#414868"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#2ac3de"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#eee8d5"
bright_black = "#24283b"
bright_red = "#ff4499"
bright_green = "#73daca"
bright_yellow = "#657b83"
bright_blue = "#839496"
bright_magenta = "#ff007c"
bright_cyan = "#93a1a1"
bright_white = "#fdf6e3"

[[themes]]
name = "catppuccin-latte"
[themes.palette]
background = "#eff1f5"
foreground = "#4c4f69"
black = "#eff1f5"
blue = "#1e66f5"
cyan = "#04a5e5"
green = "#40a02b"
magenta = "#8839ef"
red = "#d20f39"
white = "#4c4f69"
yellow = "#df8e1d"
bright_black = "#eff1f5"
bright_blue = "#1e66f5"
bright_cyan = "#04a5e5"
bright_green = "#40a02b"
bright_magenta = "#8839ef"
bright_red = "#d20f39"
bright_white = "#4c4f69"
bright_yellow = "#df8e1d"

[themes.component_style]
selection = { bg = "#ccd0da", modifiers = ["Bold"] }
block_title = { fg = "Magenta" }
playback_track = { fg = "Cyan", modifiers = ["Bold"] }
playback_album = { fg = "Yellow" }
playback_metadata = { fg = "Blue" }
playback_progress_bar = { bg = "#ccd0da", fg = "Green" }
current_playing = { fg = "Green", modifiers = ["Bold"] }
page_desc = { fg = "Cyan", modifiers = ["Bold"] }
table_header = { fg = "Blue" }
border = {}
playback_status = { fg = "Cyan", modifiers = ["Bold"] }
playback_artists = { fg = "Cyan", modifiers = ["Bold"] }
playlist_desc = { fg = "#6c6f85" }

[[themes]]
name = "catppuccin-frappe"
[themes.palette]
background = "#303446"
foreground = "#c6d0f5"
black = "#303446"
blue = "#8caaee"
cyan = "#99d1db"
green = "#a6d189"
magenta = "#ca9ee6"
red = "#e78284"
white = "#c6d0f5"
yellow = "#e5c890"
bright_black = "#303446"
bright_blue = "#8caaee"
bright_cyan = "#99d1db"
bright_green = "#a6d189"
bright_magenta = "#ca9ee6"
bright_red = "#e78284"
bright_white = "#c6d0f5"
bright_yellow = "#e5c890"

[themes.component_style]
selection = { bg = "#414559", modifiers = ["Bold"] }
block_title = { fg = "Magenta" }
playback_track = { fg = "Cyan", modifiers = ["Bold"] }
playback_album = { fg = "Yellow" }
playback_metadata = { fg = "Blue" }
playback_progress_bar = { bg = "#414559", fg = "Green" }
current_playing = { fg = "Green", modifiers = ["Bold"] }
page_desc = { fg = "Cyan", modifiers = ["Bold"] }
table_header = { fg = "Blue" }
border = {}
playback_status = { fg = "Cyan", modifiers = ["Bold"] }
playback_artists = { fg = "Cyan", modifiers = ["Bold"] }
playlist_desc = { fg = "#a5adce" }

[[themes]]
name = "catppuccin-macchiato"
[themes.palette]
background = "#24273a"
foreground = "#cad3f5"
black = "#24273a"
blue = "#8aadf4"
cyan = "#91d7e3"
green = "#a6da95"
magenta = "#c6a0f6"
red = "#ed8796"
white = "#cad3f5"
yellow = "#eed49f"
bright_black = "#24273a"
bright_blue = "#8aadf4"
bright_cyan = "#91d7e3"
bright_green = "#a6da95"
bright_magenta = "#c6a0f6"
bright_red = "#ed8796"
bright_white = "#cad3f5"
bright_yellow = "#eed49f"

[themes.component_style]
selection = { bg = "#363a4f", modifiers = ["Bold"] }
block_title = { fg = "Magenta" }
playback_track = { fg = "Cyan", modifiers = ["Bold"] }
playback_album = { fg = "Yellow" }
playback_metadata = { fg = "Blue" }
playback_progress_bar = { bg = "#363a4f", fg = "Green" }
current_playing = { fg = "Green", modifiers = ["Bold"] }
page_desc = { fg = "Cyan", modifiers = ["Bold"] }
table_header = { fg = "Blue" }
border = {}
playback_status = { fg = "Cyan", modifiers = ["Bold"] }
playback_artists = { fg = "Cyan", modifiers = ["Bold"] }
playlist_desc = { fg = "#a5adcb" }

[[themes]]
name = "catppuccin-mocha"
[themes.palette]
background = "#1e1e2e"
foreground = "#cdd6f4"
black = "#1e1e2e"
blue = "#89b4fa"
cyan = "#89dceb"
green = "#a6e3a1"
magenta = "#cba6f7"
red = "#f38ba8"
white = "#cdd6f4"
yellow = "#f9e2af"
bright_black = "#1e1e2e"
bright_blue = "#89b4fa"
bright_cyan = "#89dceb"
bright_green = "#a6e3a1"
bright_magenta = "#cba6f7"
bright_red = "#f38ba8"
bright_white = "#cdd6f4"
bright_yellow = "#f9e2af"

[themes.component_style]
selection = { bg = "#313244", modifiers = ["Bold"] }
block_title = { fg = "Magenta" }
playback_track = { fg = "Cyan", modifiers = ["Bold"] }
playback_album = { fg = "Yellow" }
playback_metadata = { fg = "Blue" }
playback_progress_bar = { bg = "#313244", fg = "Green" }
current_playing = { fg = "Green", modifiers = ["Bold"] }
page_desc = { fg = "Cyan", modifiers = ["Bold"] }
table_header = { fg = "Blue" }
border = {}
playback_status = { fg = "Cyan", modifiers = ["Bold"] }
playback_artists = { fg = "Cyan", modifiers = ["Bold"] }
playlist_desc = { fg = "#a6adc8" }
